"""reporter.py – Formats enrichment results as Markdown or JSON."""

from typing import Any


def build_markdown_report(results: list[dict[str, Any]]) -> str:
    lines = ["# SOC IOC Enrichment Report", ""]

    for r in results:
        ioc_val  = r.get("ioc", "N/A")
        ioc_type = r.get("type", "unknown").upper()
        lines += [f"## `{ioc_val}`  `[{ioc_type}]`", ""]

        enrichments = r.get("enrichments", {})

        # VirusTotal
        vt = enrichments.get("virustotal", {})
        lines.append("### VirusTotal")
        if vt.get("status") == "ok":
            mal   = vt.get("malicious", 0)
            total = vt.get("total_engines", 0)
            verdict = "**MALICIOUS**" if mal > 0 else "Clean"
            lines += [
                f"- Verdict: {verdict}",
                f"- Malicious detections: `{mal}` / `{total}` engines",
                f"- Suspicious: `{vt.get('suspicious', 0)}`",
                f"- Reputation score: `{vt.get('reputation', 'N/A')}`",
                f"- Country: `{vt.get('country', 'N/A')}`",
                f"- AS Owner: `{vt.get('as_owner', 'N/A')}`",
                f"- Tags: {', '.join(vt.get('tags', [])) or 'none'}",
            ]
        elif vt.get("status") == "not_found":
            lines.append("- No data found in VirusTotal.")
        else:
            lines.append(f"- Status: `{vt.get('status')}` – {vt.get('reason', '')}")

        lines.append("")

        # AbuseIPDB
        if "abuseipdb" in enrichments:
            ab = enrichments["abuseipdb"]
            lines.append("### AbuseIPDB")
            if ab.get("status") == "ok":
                conf = ab.get("abuse_confidence", 0)
                verdict = "**HIGH RISK**" if conf >= 75 else ("Moderate" if conf >= 25 else "Low Risk")
                lines += [
                    f"- Abuse Confidence: `{conf}%`  ({verdict})",
                    f"- Total Reports: `{ab.get('total_reports', 0)}`",
                    f"- ISP: `{ab.get('isp', 'N/A')}`",
                    f"- Country: `{ab.get('country_code', 'N/A')}`",
                    f"- Tor Exit Node: `{ab.get('is_tor', False)}`",
                    f"- Last Reported: `{ab.get('last_reported_at', 'N/A')}`",
                ]
            else:
                lines.append(f"- Status: `{ab.get('status')}` – {ab.get('reason', '')}")
            lines.append("")

        # WHOIS
        if "whois" in enrichments:
            wh = enrichments["whois"]
            lines.append("### WHOIS")
            if wh.get("status") == "ok":
                lines += [
                    f"- Registrar: `{wh.get('registrar', 'N/A')}`",
                    f"- Created: `{wh.get('creation_date', 'N/A')}`",
                    f"- Expires: `{wh.get('expiration_date', 'N/A')}`",
                    f"- Org: `{wh.get('org', 'N/A')}`",
                    f"- Country: `{wh.get('country', 'N/A')}`",
                ]
            else:
                lines.append(f"- Status: `{wh.get('status')}` – {wh.get('reason', '')}")
            lines.append("")

        lines += ["---", ""]

    lines.append("_Generated by [soc-ioc-enricher](https://github.com/AnkSingh2-secOps/soc-ioc-enricher)_")
    return "\n".join(lines)
